use std::collections::HashMap;

#[allow(clippy::too_many_lines)]
pub fn get() -> HashMap<&'static str, &'static str> {
    [
        ("0", "Generating world terrain"),
        ("10", "Generating surface caves"),
        ("11", "Generating jungle"),
        ("12", "Generating floating islands"),
        ("13", "Adding mushroom patches"),
        ("14", "Placing mud in the dirt"),
        ("15", "Adding silt"),
        ("16", "Adding shinies"),
        ("17", "Adding webs"),
        ("18", "Creating underworld"),
        ("19", "Adding water bodies"),
        ("1", "Adding sand"),
        ("20", "Making the world evil"),
        ("21", "Generating mountain caves"),
        ("22", "Creating beaches"),
        ("23", "Adding gems"),
        ("24", "Gravitating sand"),
        ("25", "Cleaning up dirt backgrounds"),
        ("26", "Placing altars"),
        ("27", "Settling liquids"),
        ("28", "Placing life crystals"),
        ("29", "Placing statues"),
        ("2", "Generating hills"),
        ("30", "Hiding treasure"),
        ("31", "Hiding more treasure"),
        ("32", "Hiding jungle treasure"),
        ("33", "Hiding water treasure"),
        ("34", "Placing traps"),
        ("35", "Placing breakables"),
        ("36", "Placing hellforges"),
        ("37", "Spreading grass"),
        ("38", "Growing cacti"),
        ("39", "Planting sunflowers"),
        ("3", "Putting dirt behind dirt"),
        ("40", "Planting trees"),
        ("41", "Planting herbs"),
        ("42", "Planting weeds"),
        ("43", "Growing vines"),
        ("44", "Planting flowers"),
        ("45", "Planting mushrooms"),
        ("46", "Freeing unused resources"),
        ("47", "Resetting game objects"),
        ("48", "Progressing world..."),
        ("49", "Saving world data:"),
        ("4", "Placing rocks in the dirt"),
        ("50", "Backing up world file"),
        ("51", "Loading world data:"),
        ("52", "Checking tile alignment:"),
        ("53", "Load failed!"),
        ("54", "No backup found."),
        ("55", "Finding tile frames:"),
        ("56", "Adding snow"),
        ("57", "World"),
        ("58", "Creating dungeon"),
        ("59", "A meteorite has landed!"),
        ("5", "Placing dirt in the rocks"),
        ("60", "Smoothing the world"),
        ("61", "Mossification"),
        ("62", "Gemification"),
        ("63", "Making cave walls"),
        ("64", "Growing spider caves"),
        ("65", "Clearing map data:"),
        ("66", "Saving map data:"),
        ("67", "Loading map data:"),
        ("68", "Drawing map:"),
        ("69", "Creating waterfalls"),
        ("6", "Adding clay"),
        ("70", "Creating jungle ruins"),
        ("71", "Creating hornet nests"),
        ("72", "Making the world bloody"),
        ("73", "Validating world save:"),
        ("74", "Slime is falling from the sky!"),
        ("75", "Slime has stopped falling from the sky."),
        ("76", "Generating structures"),
        ("77", "Adding more grass"),
        ("78", "Desertification"),
        ("79", "Weathering caverns"),
        ("7", "Making random holes"),
        ("80", "Chiseling marble"),
        ("81", "Growing granite"),
        ("8", "Generating small caves"),
        ("9", "Generating large caves"),
        ("82", "Disarming broken traps"),
        ("83", "Growing rich mahogany"),
        ("84", "Clean up"),
        ("85", "Felling trees"),
        ("86", "Final clean up"),
        ("87", "Finalizing world"),
        ("88", "Growing water plants"),
        ("89", "Placing objects"),
        ("90", "Forming the depths"),
        ("91", "Not placing traps"),
        ("92", "A meteor shower is happening!"),
        ("93", "Coins descend from the heavens!"),
    ]
    .iter()
    .copied()
    .collect()
}
